# Generated by Django 2.2.13 on 2020-10-03 08:18

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30, unique=True, verbose_name='院校名称')),
                ('school_first_name', models.CharField(default='', max_length=30, null=True, verbose_name='院校首字母')),
                ('contacts', models.CharField(max_length=30, verbose_name='院校联系人')),
                ('school_class', models.CharField(default='大学', max_length=30, null=True, verbose_name='院校类型')),
                ('contacts_telephone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('1[3456789]\\d{9}', message='请输入正确格式的手机号码！')], verbose_name='手机号')),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('\\w{6,16}', message='请输入正确格式的密码！')], verbose_name='密码')),
                ('audit_status', models.CharField(default='待审核', max_length=20, null=True, verbose_name='审核状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 10, 3, 8, 18, 11, 762260, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=30, verbose_name='指导教师姓名')),
                ('instructor_telephone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('1[3456789]\\d{9}', message='请输入正确格式的手机号码！')], verbose_name='手机号')),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('\\w{6,16}', message='请输入正确格式的密码！')], verbose_name='密码')),
                ('id_number', models.CharField(default='', max_length=30, verbose_name='身份证号')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 10, 3, 8, 18, 11, 764262, tzinfo=utc))),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='backManage.College')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_username', models.CharField(max_length=30, verbose_name='用户名')),
                ('judge_name', models.CharField(max_length=30, verbose_name='评委姓名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('judge_type', models.CharField(max_length=30, verbose_name='评委类型')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=30, verbose_name='成员姓名')),
                ('student_number', models.CharField(default='', max_length=30, verbose_name='学号')),
                ('telephone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('1[3456789]\\d{9}', message='请输入正确格式的手机号码！')], verbose_name='手机号')),
                ('id_number', models.CharField(default='', max_length=30, verbose_name='身份证号')),
                ('grade', models.CharField(default='大二', max_length=30, verbose_name='年级')),
                ('major', models.CharField(default='统计学', max_length=30, verbose_name='专业')),
                ('class_in_school', models.CharField(default='统计0班', max_length=30, verbose_name='班级')),
                ('is_captain', models.CharField(default='否', max_length=2, verbose_name='是否为队长')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 10, 3, 8, 18, 11, 766264, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='本科生组', max_length=30, verbose_name='组别')),
                ('work_group', models.CharField(default='大数据应用类', max_length=30, verbose_name='参赛项目类别')),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('\\w{6,16}', message='请输入正确格式的密码！')], verbose_name='密码')),
                ('tele_member2', models.CharField(max_length=11, verbose_name='成员2手机号')),
                ('tele_member3', models.CharField(max_length=11, verbose_name='成员3手机号')),
                ('work_id', models.CharField(default='20200000', max_length=11, verbose_name='项目编号')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 10, 3, 8, 18, 11, 768266, tzinfo=utc))),
                ('status', models.CharField(default='待审核', max_length=20, verbose_name='状态')),
                ('first_instru', models.ManyToManyField(null=True, related_name='team_first', to='backManage.Instructor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backManage.College')),
                ('second_instru', models.ManyToManyField(null=True, related_name='team_second', to='backManage.Instructor')),
                ('telephone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='backManage.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 10, 3, 8, 18, 11, 776245, tzinfo=utc))),
                ('paper', models.FileField(upload_to='paper', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'pdf'], message='文件格式必须为doc,docx,pdf格式')], verbose_name='作品')),
                ('status', models.CharField(default='待审核', max_length=20, verbose_name='状态')),
                ('work_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='backManage.Team')),
            ],
        ),
    ]
