# Generated by Django 2.2.13 on 2020-10-03 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0002_auto_20201003_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 11, 47, 2, 104914, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='college',
            name='audit_status',
            field=models.CharField(default='待审核', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='college',
            name='school_class',
            field=models.CharField(default='大学', max_length=30, verbose_name='院校类型'),
        ),
        migrations.AlterField(
            model_name='college',
            name='school_first_name',
            field=models.CharField(default='', max_length=30, verbose_name='院校首字母'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 11, 47, 2, 106915, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 11, 47, 2, 108917, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 11, 47, 2, 112892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(default='待完善信息', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 11, 47, 2, 120908, tzinfo=utc)),
        ),
    ]
