# Generated by Django 2.2.13 on 2020-10-03 12:19

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0003_auto_20201003_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 19, 41, 949436, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='college',
            name='school',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('[\\u4E00-\\u9FA5]+', message='请输入汉字,注意不要加空格！')], verbose_name='院校名称'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 19, 41, 951461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 19, 41, 953463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 19, 41, 955466, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 19, 41, 962471, tzinfo=utc)),
        ),
    ]
