# Generated by Django 2.2.13 on 2020-10-03 12:27

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0005_auto_20201003_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 27, 47, 543455, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='college',
            name='contacts',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[\\u4E00-\\u9FA5]+', message='姓名请输入汉字,注意不要加空格！')], verbose_name='院校联系人'),
        ),
        migrations.AlterField(
            model_name='college',
            name='school',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('[\\u4E00-\\u9FA5]+', message='院校名请输入汉字,注意不要加空格！')], verbose_name='院校名称'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 27, 47, 545462, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 27, 47, 548487, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 27, 47, 550488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 27, 47, 558497, tzinfo=utc)),
        ),
    ]
