# Generated by Django 2.2.13 on 2020-10-03 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0006_auto_20201003_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 13, 25, 26, 989967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 13, 25, 26, 991968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 13, 25, 26, 993970, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 13, 25, 26, 997945, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='tele_member2',
            field=models.CharField(max_length=11, null=True, verbose_name='成员2手机号'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tele_member3',
            field=models.CharField(max_length=11, null=True, verbose_name='成员3手机号'),
        ),
        migrations.AlterField(
            model_name='team',
            name='work_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 13, 25, 27, 4959, tzinfo=utc)),
        ),
    ]
