# Generated by Django 2.2.13 on 2020-10-03 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0007_auto_20201003_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='instructor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='instructor_telephone',
            new_name='telephone',
        ),
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 14, 3, 26, 461479, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 14, 3, 26, 463510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 14, 3, 26, 466512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 14, 3, 26, 468514, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 14, 3, 26, 475520, tzinfo=utc)),
        ),
    ]
