# Generated by Django 2.2.13 on 2020-10-04 00:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0012_auto_20201004_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='first_instru',
        ),
        migrations.RemoveField(
            model_name='team',
            name='second_instru',
        ),
        migrations.AddField(
            model_name='team',
            name='instru',
            field=models.ManyToManyField(null=True, related_name='team', to='backManage.Instructor'),
        ),
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 0, 37, 52, 891858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 0, 37, 52, 893860, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 0, 37, 52, 895861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 0, 37, 52, 897863, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 0, 37, 52, 902869, tzinfo=utc)),
        ),
    ]
