# Generated by Django 2.2.13 on 2020-10-04 01:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0015_auto_20201004_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='is_first',
        ),
        migrations.AddField(
            model_name='team',
            name='first_instru_telephone',
            field=models.CharField(default='00000', max_length=11, verbose_name='第一指导教师手机号'),
        ),
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 1, 35, 49, 322499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 1, 35, 49, 324500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 1, 35, 49, 326503, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 1, 35, 49, 329476, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 1, 35, 49, 334509, tzinfo=utc)),
        ),
    ]
