# Generated by Django 2.2.13 on 2020-10-04 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0017_auto_20201004_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 11, 24, 10, 271055, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 11, 24, 10, 273057, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 11, 24, 10, 277052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 11, 24, 10, 279061, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_instru_telephone',
            field=models.CharField(default='', max_length=11, verbose_name='第一指导教师手机号'),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 11, 24, 10, 284067, tzinfo=utc)),
        ),
    ]
