# Generated by Django 2.2.13 on 2020-10-05 03:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0020_auto_20201005_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='score_1',
            field=models.PositiveIntegerField(default=0, verbose_name='得分1'),
        ),
        migrations.AddField(
            model_name='work',
            name='score_2',
            field=models.PositiveIntegerField(default=0, verbose_name='得分2'),
        ),
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 3, 46, 57, 124630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 3, 46, 57, 125631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 3, 46, 57, 128634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 3, 46, 57, 130636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 3, 46, 57, 136634, tzinfo=utc)),
        ),
    ]
