# Generated by Django 2.2.13 on 2020-10-05 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0024_auto_20201005_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='number_team',
            field=models.PositiveIntegerField(default=20, verbose_name='得分2'),
        ),
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 3, 46, 786904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 3, 46, 788907, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 3, 46, 791910, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 3, 46, 794943, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 3, 46, 798945, tzinfo=utc)),
        ),
    ]
