# Generated by Django 2.2.13 on 2020-10-05 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0026_auto_20201005_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='judge_works',
            field=models.ManyToManyField(null=True, related_name='judge', to='backManage.Work'),
        ),
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 7, 56, 440599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 7, 56, 442601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 7, 56, 444603, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 7, 56, 448611, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 7, 56, 454641, tzinfo=utc)),
        ),
    ]
