# Generated by Django 2.2.13 on 2020-10-05 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0027_auto_20201005_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 36, 50, 893328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='college',
            name='number_team',
            field=models.PositiveIntegerField(default=20, verbose_name='名额数量'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 36, 50, 895329, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 36, 50, 898332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 36, 50, 902329, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 5, 36, 50, 908363, tzinfo=utc)),
        ),
    ]
