# Generated by Django 2.2.13 on 2020-10-07 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0031_auto_20201006_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='detail_1',
            field=models.CharField(default='', max_length=100, verbose_name='评价1'),
        ),
        migrations.AddField(
            model_name='work',
            name='detail_2',
            field=models.CharField(default='', max_length=100, verbose_name='评价2'),
        ),
        migrations.AddField(
            model_name='work',
            name='judge_2_username',
            field=models.CharField(default='', max_length=20, verbose_name='评委2'),
        ),
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 4, 12, 36, 795907, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 4, 12, 36, 797937, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 4, 12, 36, 810928, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 4, 12, 36, 799938, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 4, 12, 36, 802941, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 4, 12, 36, 806946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='judge_1_username',
            field=models.CharField(default='', max_length=20, verbose_name='评委1'),
        ),
    ]
