# Generated by Django 2.2.13 on 2020-10-07 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0032_auto_20201007_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='judge1_is_review',
            field=models.CharField(default='否', max_length=2, verbose_name='评委1是否提交评分'),
        ),
        migrations.AddField(
            model_name='work',
            name='judge2_is_review',
            field=models.CharField(default='否', max_length=2, verbose_name='评委2是否提交评分'),
        ),
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 53, 21, 455056, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 53, 21, 457057, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 53, 21, 471047, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 53, 21, 459057, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 53, 21, 463032, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 53, 21, 468044, tzinfo=utc)),
        ),
    ]
