# Generated by Django 2.2.13 on 2020-10-07 09:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0033_auto_20201007_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='detail_1',
        ),
        migrations.RemoveField(
            model_name='work',
            name='detail_2',
        ),
        migrations.RemoveField(
            model_name='work',
            name='judge1_is_review',
        ),
        migrations.RemoveField(
            model_name='work',
            name='judge2_is_review',
        ),
        migrations.RemoveField(
            model_name='work',
            name='judge_1_username',
        ),
        migrations.RemoveField(
            model_name='work',
            name='judge_2_username',
        ),
        migrations.RemoveField(
            model_name='work',
            name='score_1',
        ),
        migrations.RemoveField(
            model_name='work',
            name='score_2',
        ),
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 9, 58, 54, 95316, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 9, 58, 54, 97317, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 9, 58, 54, 117309, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 9, 58, 54, 99319, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 9, 58, 54, 101321, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 9, 58, 54, 113305, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_score', models.PositiveIntegerField(default=0, verbose_name='得分')),
                ('judge_detail', models.CharField(default='', max_length=100, verbose_name='评价')),
                ('judge_is_review', models.CharField(default='否', max_length=2, verbose_name='评委是否提交评分')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='backManage.Judge')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='backManage.Work')),
            ],
        ),
    ]
